# Generated by Django 6.0.6 on 2026-07-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advantage',
        ),
    ]
